/**
 * App Redux Action Types
 */
export const COLLAPSED_SIDEBAR = 'COLLAPSED_SIDEBAR';
export const DARK_MODE = 'DARK_MODE';
export const BOXED_LAYOUT = 'BOXED_LAYOUT';
export const RTL_LAYOUT = 'RTL_LAYOUT';
export const MINI_SIDEBAR = 'MINI_SIDEBAR';
export const SEARCH_FORM_ENABLE = 'SEARCH_FORM_ENABLE';
export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';
export const TOGGLE_SIDEBAR_IMAGE = 'TOGGLE_SIDEBAR_IMAGE';
export const SET_SIDEBAR_IMAGE = 'SET_SIDEBAR_IMAGE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const START_USER_TOUR = 'START_USER_TOUR';
export const STOP_USER_TOUR = 'STOP_USER_TOUR';
export const TOGGLE_DARK_SIDENAV = 'TOGGLE_DARK_SIDENAV';
// Chat App Actions
export const CHAT_WITH_SELECTED_USER = 'CHAT_WITH_SELECTED_USER';
export const SEND_MESSAGE_TO_USER = 'SEND_MESSAGE_TO_USER';
export const UPDATE_USERS_SEARCH = 'UPDATE_USERS_SEARCH';
export const SEARCH_USERS = 'SEARCH_USERS';
export const GET_RECENT_CHAT_USERS = 'GET_RECENT_CHAT_USERS';
// Agency Sidebar
export const AGENCY_TOGGLE_MENU = 'AGENCY_TOGGLE_MENU';
export const CHANGE_AGENCY_LAYOUT_BG = 'CHANGE_AGENCY_LAYOUT_BG';
// Mail App
export const GET_EMAILS = 'GET_EMAILS';
export const GET_EMAIL_SUCCESS = 'GET_EMAIL_SUCCESS';
export const GET_EMAIL_FAILURE = 'GET_EMAIL_FAILURE';
export const SET_EMAIL_AS_STAR = 'SET_EMAIL_AS_STAR';
export const READ_EMAIL = 'READ_EMAIL';
export const HIDE_LOADING_INDICATOR = 'HIDE_LOADING_INDICATOR';
export const FETCH_EMAILS = 'FETCH_EMAILS';
export const ON_SELECT_EMAIL = 'ON_SELECT_EMAIL';
export const UPDATE_EMAIL_SEARCH = 'UPDATE_EMAIL_SEARCH';
export const SEARCH_EMAIL = 'SEARCH_EMAIL';
export const ON_DELETE_MAIL = 'ON_DELETE_MAIL';
export const ON_BACK_PRESS_NAVIGATE_TO_EMAIL_LISTING =
  'ON_BACK_PRESS_NAVIGATE_TO_EMAIL_LISTING';
export const GET_SENT_EMAILS = 'GET_SENT_EMAILS';
export const GET_INBOX = 'GET_INBOX';
export const GET_DRAFTS_EMAILS = 'GET_DRAFTS_EMAILS';
export const GET_SPAM_EMAILS = 'GET_SPAM_EMAILS';
export const GET_TRASH_EMAILS = 'GET_TRASH_EMAILS';
export const ON_EMAIL_MOVE_TO_FOLDER = 'ON_EMAIL_MOVE_TO_FOLDER';
export const SELECT_ALL_EMAILS = 'SELECT_ALL_EMAILS';
export const UNSELECT_ALL_EMAILS = 'UNSELECT_ALL_EMAILS';
export const ON_SEND_EMAIL = 'ON_SEND_EMAIL';
export const EMAIL_SENT_SUCCESSFULLY = 'EMAIL_SENT_SUCCESSFULLY';
export const FILTER_EMAILS_WITH_LABELS = 'FILTER_EMAILS_WITH_LABELS';
export const ADD_LABELS_INTO_EMAILS = 'ADD_LABELS_INTO_EMAILS';
// sidebar
export const TOGGLE_MENU = 'TOGGLE_MENU';
// ToDo App
export const GET_TODOS = 'GET_TODOS';
export const FETCH_TODOS = 'FETCH_TODOS';
export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const ON_SELECT_TODO = 'ON_SELECT_TODO';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';
export const ON_BACK_TO_TODOS = 'ON_BACK_TO_TODOS';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const MARK_AS_STAR_TODO = 'MARK_AS_STAR_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const ADD_LABELS_INTO_THE_TASK = 'ADD_LABELS_INTO_THE_TASK';
export const GET_ALL_TODO = 'GET_ALL_TODO';
export const GET_COMPLETED_TODOS = 'GET_COMPLETED_TODOS';
export const GET_DELETED_TODOS = 'GET_DELETED_TODOS';
export const GET_STARRED_TODOS = 'GET_STARRED_TODOS';
export const GET_FILTER_TODOS = 'GET_FILTER_TODOS';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const UPDATE_TASK_TITLE = 'UPDATE_TASK_TITLE';
export const UPDATE_TASK_DESCRIPTION = 'UPDATE_TASK_DESCRIPTION';
export const CHANGE_TASK_ASSIGNER = 'CHANGE_TASK_ASSIGNER';
export const ON_CHECK_BOX_TOGGLE_TODO_ITEM = 'ON_CHECK_BOX_TOGGLE_TODO_ITEM';
export const SELECT_ALL_TODO = 'SELECT_ALL_TODO';
export const GET_UNSELECTED_ALL_TODO = 'GET_UNSELECTED_ALL_TODO';
export const SELECT_STARRED_TODO = 'SELECT_STARRED_TODO';
export const SELECT_UNSTARRED_TODO = 'SELECT_UNSTARRED_TODO';
export const ON_LABEL_SELECT = 'ON_LABEL_SELECT';
export const ON_LABEL_MENU_ITEM_SELECT = 'ON_LABEL_MENU_ITEM_SELECT';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const SEARCH_TODO = 'SEARCH_TODO';

// config
export const GET_CONFIG = 'GET_CONFIG';
export const SET_CONFIG = 'SET_CONFIG';
export const RESET_CONFIG = 'RESET_CONFIG';

// Auth Actions
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS';
export const CHECK_TOKEN_ERROR = 'CHECK_TOKEN_ERROR';

//customer action
export const GET_ALL_CUSTOMER = 'GET_ALL_CUSTOMER';
export const GET_CUSTOMER_DETAIL = 'GET_CUSTOMER_DETAIL';
export const ADD_A_CUSTOMER = 'ADD_A_CUSTOMER';
export const UPDATE_A_CUSTOMER_IN_LIST = 'UPDATE_A_CUSTOMER_IN_LIST';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const DELETE_A_CUSTOMER_IN_LIST = 'DELETE_A_CUSTOMER_IN_LIST';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

// group action
export const GET_ALL_GROUP = 'GET_ALL_GROUP';
export const GET_GROUP_DETAIL = 'GET_GROUP_DETAIL';
export const ADD_A_GROUP = 'ADD_A_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const GET_LIST_ASSETS = 'GET_LIST_ASSETS';
// asset action
export const GET_ALL_ASSET = 'GET_ALL_ASSET';
export const GET_ASSET_DETAIL = 'GET_ASSET_DETAIL';
export const ADD_A_ASSET = 'ADD_A_ASSET';
export const UPDATE_ASSET = 'UPDATE_ASSET';
export const DELETE_ASSET = 'DELETE_ASSET';
// category action
export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const ADD_A_CATEGORIES = 'ADD_A_CATEGORIES';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_PARENT = 'UPDATE_PARENT';
export const GET_ALL_PARENT = 'GET_ALL_PARENT';
// destination action
export const GET_ALL_DESTINATION = 'GET_ALL_DESTINATION';
export const ADD_A_DESTINATION = 'ADD_A_DESTINATION';
export const UPDATE_DESTINATION = 'UPDATE_DESTINATION';
export const DELETE_DESTINATION = 'DELETE_DESTINATION';
// country action
export const GET_ALL_COUNTRY = 'GET_ALL_COUNTRY';
export const ADD_A_COUNTRY = 'ADD_A_COUNTRY';
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';
export const DELETE_COUNTRY = 'DELETE_COUNTRY';
export const UPDATE_STATUS_COUNTRY = 'UPDATE_STATUS_COUNTRY';
// tour action
export const GET_ALL_TOUR = 'GET_ALL_TOUR';
export const ADD_A_TOUR = 'ADD_A_TOUR';
export const UPDATE_TOUR = 'UPDATE_TOUR';
export const UPDATE_DEPARTURE_IN_TOUR = 'UPDATE_DEPARTURE_IN_TOUR';
export const DELETE_TOUR = 'DELETE_TOUR';
export const GET_TOUR_DETAIL = 'GET_TOUR_DETAIL';
export const GET_TOUR_RATES = 'GET_TOUR_RATES';

// airline action
export const GET_ALL_AIRLINES = 'GET_ALL_AIRLINES';
export const ADD_A_AIRLINE = 'ADD_A_AIRLINE';
export const UPDATE_AIRLINE = 'UPDATE_AIRLINE';
export const DELETE_AIRLINE = 'DELETE_AIRLINE';
export const UPDATE_STATUS_AIRLINE = 'UPDATE_STATUS_AIRLINE';

// contract action
export const GET_ALL_CONTRACT = 'GET_ALL_CONTRACT';
// ACCOUNT action
export const GET_ALL_ACCOUNT = 'GET_ALL_ACCOUNT';
export const ADD_A_ACCOUNT = 'ADD_A_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const BATCH_DELETE = 'BATCH_DELETE';

//Product type
export const LIST_PRODUCT = 'LIST_PRODUCT';
export const LIST_PRODUCT_SUCCESS = 'LIST_PRODUCT_SUCCESS';
export const LIST_PRODUCT_ERROR = 'LIST_PRODUCT_ERROR';
export const SAVE_PRODUCT = 'SAVE_PRODUCT';
export const SAVE_PRODUCT_ERROR = 'SAVE_PRODUCT_ERROR';
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
//upload image
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';

//Reviews
export const LIST_REVIEW = 'LIST_REVIEW';
export const ADD_REVIEW = 'ADD_REVIEW';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const UPDATE_STATUS_REVIEW = 'UPDATE_STATUS_REVIEW';

//Itineraries
export const LIST_ITINERARIES = 'LIST_ITINERARIES';
//export const LIST_PRODUCT_SUCCESS = 'LIST_PRODUCT_SUCCESS';
//export const LIST_PRODUCT_ERROR = 'LIST_PRODUCT_ERROR';
export const ADD_ITINERARIES = 'ADD_ITINERARIES';
export const UPDATE_ITINERARIES = 'UPDATE_ITINERARIES';
export const DELETE_ITINERARIES = 'DELETE_ITINERARIES';

// Common type
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const PUBLISH_STATUSES = 'PUBLISH_STATUSES';
export const UNPUBLISH_STATUSES = 'UNPUBLISH_STATUSES';

//file manager
export const GET_LIST_FILE_AND_FOLDER = 'GET_LIST_FILE_AND_FOLDER';
export const CREATE_FOLDER = 'CREATE_FOLDER';
export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_IMG = "UPLOAD_IMG";

