const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
const CHANGE_USER_DATA = 'CHANGE_USER_DATA';
const CHANGE_CONFIG = 'CHANGE_CONFIG';
const CHANGE_END_POINT = 'CHANGE_END_POINT';
const LOGIN_STATUS = 'LOGIN_STATUS';
const HOST_LOGINED_STATUS = 'HOST_LOGINED_STATUS';
const WORKER_LOGINED_STATUS = 'WORKER_LOGINED_STATUS';
const REGISTER_STATUS = 'REGISTER_STATUS';
const CHANGE_CHAT_STATUS = 'CHANGE_CHAT_STATUS';
const CHANGE_COUNT_UNREAD_CHAT = 'CHANGE_COUNT_UNREAD_CHAT';
const CHANGE_DATA_PRODUCT_CREATE = 'CHANGE_DATA_PRODUCT_CREATE';

const CHANGE_APP_STATE = 'CHANGE_APP_STATE';
const CHANGE_PERMISSION_LOCATION = 'CHANGE_PERMISSION_LOCATION';
const LOADING_STATUS = 'LOADING_STATUS';
const UPDATE_USERDATA = 'UPDATE_USER';
const CREATE_USERDATA = 'CREATE_USER';
const RELOAD_MY_JOBS = 'RELOAD_MY_JOBS';
const RELOAD_LIST_JOB = 'RELOAD_LIST_JOB';
const RELOAD_LIST_PRODUCT = 'RELOAD_LIST_PRODUCT';
const RESET_RELOAD_MY_JOBS = 'RESET_RELOAD_MY_JOBS';
const DEFAULT_DATA_PRODUCT_CREATE = 'DEFAULT_DATA_PRODUCT_CREATE';
const RELOAD_MY_PRODUCT = 'RELOAD_MY_PRODUCT';

const CHANGE_DEEP_LINK = 'CHANGE_DEEP_LINK';
export {
	RESET_RELOAD_MY_JOBS,
	RELOAD_LIST_PRODUCT,
	RELOAD_LIST_JOB,
	CHANGE_COUNT_UNREAD_CHAT,
	CHANGE_PERMISSION_LOCATION,
	CHANGE_APP_STATE,
	CHANGE_CHAT_STATUS,
	CHANGE_DEEP_LINK,
	CHANGE_CONFIG,
	CHANGE_USER_DATA,
	WORKER_LOGINED_STATUS,
	HOST_LOGINED_STATUS,
	CHANGE_LANGUAGE,
	LOGIN_STATUS,
	REGISTER_STATUS,
	LOADING_STATUS,
	UPDATE_USERDATA,
	CREATE_USERDATA,
	RELOAD_MY_JOBS,
	CHANGE_END_POINT,
	RELOAD_MY_PRODUCT,
	CHANGE_DATA_PRODUCT_CREATE,
	DEFAULT_DATA_PRODUCT_CREATE
};
