const languages = [
    { symbol: 'en', detail: 'English (EN)' },
    { symbol: 'vn', detail: 'Việt Nam (VN)' },
]
const languageSymbol = {
    title: "title",
    label_home: "label_home",
    label_invite: "label_invite",
    label_history: "label_history",
    label_message: "label_message",
    label_account: "label_account",
    profile: "profile",
    language: "language",
    logout: "logout",
    login: "login",
    create_job: "create_job",
    search_team_worker: "search_team_worker",
    result: "result",
    sort: "sort",
    filter: "filter",
    lastest: "lastest",
    newest: "newest",
    find_job_by_area_and_skills: "find_job_by_area_and_skills",
    alert_title_logout: "alert_title_logout",
    alert_detail_logout: "alert_detail_logout",
    no: "no",
    yes: "yes",
    point: "point",
    select_skill: "select_skill",
    create_new_job: "create_new_job",
    team: "team",
    alone: "alone",
    quantity: "quantity",
    worker_quantity: "worker_quantity",
    area: "area",
    construction: "construction",
    skill: "skill",
    select_area: "select_area",
    continute: "continute",
    select_start_date: "select_start_date",
    start_date: "start_date",
    select_number_of_days: "select_number_of_days",
    number_of_days: "number_of_days",
    salary: "salary",
    pay_day: "pay_day",
    deal: "deal",
    description: "description",
    submit: "submit",
    addPoint:"add_point",
    from: "from",
    to: "to",
    description_create_job: "description_create_job",
    worker: "worker",
    workers: "workers"

}
export { languages }
export default languageSymbol
