import * as Constant from "./constant";

const ICON_SIZE_TABBAR = 25 * Constant.ratioHeight
const ACTIVE_TINT_COLOR = Constant.ACTIVE_TINT_COLOR
const IN_ACTIVE_TINT_COLOR = Constant.NOT_ACTIVE_TINT_COLOR
const HEIGHT_TABBAR = Constant.HEIGHT_TABBAR
const BACKGROUND_TABBAR = 'transparent'
const LABEL_COLOR = 'black' 
const LABEL_SIZE = 14 * Constant.ratioHeight 
const ICON_NAME_CREATE_JOB = Constant.ICON_NAME_CREATE_JOB
const ICON_NAME_HOME = Constant.ICON_NAME_HOME
const ICON_NAME_INVITE = Constant.ICON_NAME_INVITE
const ICON_NAME_HISTORY = Constant.ICON_NAME_HISTORY
const ICON_NAME_MESSAGE = Constant.ICON_NAME_MESSAGE
const ICON_NAME_ACCOUNT = Constant.ICON_NAME_ACCOUNT
export {
    ICON_SIZE_TABBAR,
    ACTIVE_TINT_COLOR,
    IN_ACTIVE_TINT_COLOR,
    HEIGHT_TABBAR,
    BACKGROUND_TABBAR,
    LABEL_COLOR,
    LABEL_SIZE,
    ICON_NAME_CREATE_JOB,
    ICON_NAME_HOME,
    ICON_NAME_INVITE,
    ICON_NAME_HISTORY,
    ICON_NAME_MESSAGE,
    ICON_NAME_ACCOUNT
}